# Generated by Django 4.2.7 on 2025-05-30 07:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('total_objects_detected', models.IntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('processing_time', models.FloatField(default=0.0, help_text='Processing time in seconds')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Detection Result',
                'verbose_name_plural': 'Detection Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='RCNN_Model', max_length=100)),
                ('total_predictions', models.IntegerField(default=0)),
                ('average_objects_per_image', models.FloatField(default=0.0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('average_processing_time', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Model Metrics',
                'verbose_name_plural': 'Model Metrics',
            },
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('bbox_x1', models.IntegerField(help_text='Top-left x coordinate')),
                ('bbox_y1', models.IntegerField(help_text='Top-left y coordinate')),
                ('bbox_x2', models.IntegerField(help_text='Bottom-right x coordinate')),
                ('bbox_y2', models.IntegerField(help_text='Bottom-right y coordinate')),
                ('detection_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='detection.detectionresult')),
            ],
            options={
                'verbose_name': 'Detected Object',
                'verbose_name_plural': 'Detected Objects',
                'ordering': ['-confidence_score'],
            },
        ),
    ]
